### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by PascalPahlevi**
Completely Redid the Logging feature from using SLF4J to just using the JPA Repository logging. Everything up until the tests should already be working just fine.

### CODE REVIEW

**Review by Sirered — CHANGES_REQUESTED** [review]
I have resolved the merge conflicts and made sure it is running properly. I have also checked that it does update the database when a login or register succeeds or fails. I do however wish you could add another column saying what action or endpoint was being done that it was logging. So for example, if a log was a result of an attempt to login, maybe you could have a column that would contain 'auth/login' so if it was an error message, we can find out which end point was accessed that called that error message. It will also make it easier for when we want to make visualizations to show how many login requests have been made in the last week for example.

Also please Improve the Code coverage on the new LoggingService and Logs class, since it is way too low for the quality gate.

**Review by samuelcodingjourney — APPROVED** [review]
It looks good Pascal, but don't forget to check for code quality issues on SonarCloud

**Review by PeakFiction — APPROVED** [review]
Hey Pascal, thanks for the pull request, so far it's all good and the coverage is excellent. Thank you, keep on keeping on

**Review by Sirered — APPROVED** [review]
The loggingService implementation now includes endpoint name in the log and the code coverage given is sufficient

**Pull request merged**
