### PR TITLE
[RED] Added New Tests for Specified Document Verification

### PR DESCRIPTION
**Pull request by PascalPahlevi**
Currently just using to check code coverage.

### CODE REVIEW

**Review by PeakFiction — APPROVED** [review]
Nice work on the specified document verification, Pascal

**Review by samuelcodingjourney — APPROVED** [review]
Good job Pas keep it up ya

**Review by Sirered — CHANGES_REQUESTED** [review]
Please do not remove the previous iteration of verifyDocument yet, we still may need it, please readd the previous non-specific verify document

**Review by Sirered — APPROVED** [review]
Thank you Pascal. The tests are satisfactory and you have made the change that I asked.

Thank you for Your Service

**Pull request merged**
